name: Build and push container image to GHCR

# Run this workflow whenever a Dockerfile is updated.
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'workflows/Nextflow/modules/runFaQCs/Dockerfile'

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v4
            - name: Get Version
              id: get_version
              run: |
                  VERSION=$(grep -oP 'version=\K.*' workflows/Nextflow/modules/runFaQCs/Dockerfile)
                  VERSION=${VERSION:-1.0.0}
                  echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
            - name: Authenticate with container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
              # Use the `docker/build-push-action` action to build the image described
              # by the specified Dockerfile. If the build succeeds, push the image to GHCR.
              # This action uses the `tags` parameters to tag the image with the Git tag name
              # the image, respectively, with the output from the "get_version" step above.
              # For more info: https://github.com/docker/build-push-action#usage.
            - name: Build and push container image
              id: push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Docker/BBtools_Dockerfile.txt
                  push: true
                  tags: ghcr.io/LANL-Bioinformatics/edge-run_faqcs:${{ steps.get_version.outputs.version }}
