name: CI Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Apptainer 1.3.6
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6


      - name: Setup Nextflow 24.10.1
        uses: nf-core/setup-nextflow@v1
        with:
          version: "24.10.3"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run Tests (Shard ${{ matrix.shard }}/${{ strategy.job-total }})
        working-directory: ./workflows/Nextflow
        run: nf-test test --ci --shard ${{ matrix.shard }}/${{ strategy.job-total }}